# frozen_string_literal: true

# db/seeds.rb
FieldTemplate.create([
                       { name: 'build', dropdown: true, description: 'your build/body type' },
                       { name: 'cock girth', dropdown: true, description: 'how thick around your cock is; its circumference, in inches' },
                       { name: 'cock length', dropdown: true, description: 'how long your cock is, measured from the base along the top, in inches' },
                       { name: 'dominance', dropdown: true, description: 'how "dominant" are you in the sack (or dungeon)?' },
                       { name: 'drinker', dropdown: true, description: 'your habits with alcohol' },
                       { name: 'drug use', dropdown: true, description: 'your habits as they relate to recreational drug usage' },
                       { name: 'drugs of choice', dropdown: false, description: 'when/if you use recreational drugs, which one(s) do you use?' },
                       { name: 'hair color', dropdown: true, description: 'what color is your hair?' },
                       { name: 'hair length/style', dropdown: true, description: 'your hair length/style' },
                       { name: 'hiv status', dropdown: true, description: 'your HIV status' },
                       { name: 'kinks/fetishes', dropdown: false, description: 'the fuck are you into, BBro?' },
                       { name: 'location', dropdown: false, description: 'your current location (city, state)' },
                       { name: 'race', dropdown: true, description: 'your racial makeup' },
                       { name: 'sexual role', dropdown: true, description: 'do you prefer the top or the bottom bunk?' },
                       { name: 'smoker', dropdown: true, description: 'do you use cigarettes?' },
                       { name: 'body hair', dropdown: true, description: 'how hairy are you?' },
                       { name: 'height', dropdown: true, description: 'how tall are you, in feet and inches?' },
                       { name: 'weight', dropdown: true, description: 'how much do you weigh, in pounds?' },
                     ])

FieldTemplate.find_or_create_by(name: 'location').field_values.create([{ value: '[not entered]', description: 'the user hasn\'t entered his location (yet)', default: true }])

FieldTemplate.find_or_create_by(name: 'hiv status').field_values.create([
                                                                          { value: '[not entered]', description: 'the user hasn\'t entered a value for his HIV status', default: true },
                                                                          { value: '???', description: 'an unknown HIV status' },
                                                                          { value: 'neg (chasing)', description: 'HIV-negative, actively chasing HIV' },
                                                                          { value: 'neg (on PrEP)', description: 'HIV-negative, on pre-exposure prophylaxis' },
                                                                          { value: 'neg', description: 'HIV-negative' },
                                                                          { value: 'poz (undetectable)', description: 'HIV-positive, on medication, with an undetectable viral load' },
                                                                          { value: 'poz (toxic)', description: 'HIV-positive, not on medication, with a "toxic" viral load' },
                                                                          { value: 'poz', description: 'HIV-positive' },
                                                                          { value: 'other', description: 'Some other status not otherwise listed' },
                                                                        ])

FieldTemplate.find_or_create_by(name: 'sexual role').field_values.create([
                                                                           { value: '[not entered]', description: 'The user hasn\'t selected a sexual role (yet)', default: true },
                                                                           { value: 'total bottom', description: 'Never puts his dick in another man\'s ass; his dick is only for show or to flop around whilst he gets railed' },
                                                                           { value: 'bottom', description: 'Can top in an emergency' },
                                                                           { value: 'mostly bottom', description: 'Will top for the right guy' },
                                                                           { value: 'vers bottom', description: 'Predominantly bottom, but will top on occasion' },
                                                                           { value: 'versatile', description: 'Enjoys both fucking and getting fucked equally' },
                                                                           { value: 'vers top', description: 'Predominantly top, but enjoys bottoming on occasion' },
                                                                           { value: 'mostly top', description: 'Will bottom for the right guy' },
                                                                           { value: 'top', description: 'Will bottom on rare occasions' },
                                                                           { value: 'total top', description: 'Total top; no dick goes in his ass EVER' },
                                                                         ])

FieldTemplate.find_or_create_by(name: 'hair length/style').field_values.create([
                                                                                 { value: '[not entered]', description: 'The user hasn\'t selected a hair style (yet)', default: true },
                                                                                 { value: 'short', description: 'short' },
                                                                                 { value: 'military', description: 'military/crew cut' },
                                                                                 { value: 'bald', description: 'bald/shaved' },
                                                                                 { value: 'medium', description: 'medium length hair' },
                                                                                 { value: 'long', description: 'like a chick\s' },
                                                                               ])

FieldTemplate.find_or_create_by(name: 'hair color').field_values.create([
                                                                          { value: '[not entered]', description: 'The user hasn\'t selected a hair color (yet)', default: true },
                                                                          { value: 'bald', description: 'bald' },
                                                                          { value: 'black', description: 'black' },
                                                                          { value: 'blond', description: 'blond' },
                                                                          { value: 'brown', description: 'brown' },
                                                                          { value: 'dark blond', description: 'dark blond' },
                                                                          { value: 'dark brown', description: 'dark brown' },
                                                                          { value: 'dyed', description: 'dyed' },
                                                                          { value: 'gray', description: 'gray' },
                                                                          { value: 'light blond', description: 'light blond' },
                                                                          { value: 'light brown', description: 'light brown' },
                                                                          { value: 'other', description: 'some other color' },
                                                                          { value: 'red', description: 'auburn/red' },
                                                                        ])

FieldTemplate.find_or_create_by(name: 'build').field_values.create([
                                                                     { value: '[not entered]', description: 'The user hasn\'t selected a build (yet)', default: true },
                                                                     { value: 'skinny', description: 'a skinny/slim build' },
                                                                     { value: 'athletic', description: 'an athletic build' },
                                                                     { value: 'average', description: 'an average build' },
                                                                     { value: 'muscular', description: 'a muscular build' },
                                                                     { value: 'heavy-set', description: 'a heavy-set (i.e., fat) build' },
                                                                     { value: 'twink', description: 'a skinny smooth twinkish build' },
                                                                     { value: 'swimmers', description: 'a skinny athletic swimmers build' },
                                                                     { value: 'chub', description: 'a chubby (i.e., fat) build' },
                                                                     { value: 'bear', description: 'a bearish build' },
                                                                     { value: 'otter', description: 'an otterish (slim and hairy) build' },
                                                                   ])

FieldTemplate.find_or_create_by(name: 'race').field_values.create([
                                                                    { value: '[not entered]', description: 'The user hasn\'t selected a race (yet)', default: true },
                                                                    { value: 'white', description: 'Someone whose origins are in the original peoples of Europe' },
                                                                    { value: 'black', description: 'Someone whose ancestry is from any of the black racial groups of Africa' },
                                                                    { value: 'asian', description: 'Someone whose ancestry is generally Asian (e.g, Chinese, Korean, Japanese, Mongolian)' },
                                                                    { value: 'hispanic', description: 'Someone whose ancestry is generally from Latin America or Spain' },
                                                                    { value: 'american indian / alaskan native', description: 'Someone whose ancestry is ultimately Asian but whose ancestors came to the United States before Columbus' },
                                                                    { value: 'indian', description: 'Someone whose ancestry is generally from the Indian subcontinent' },
                                                                    { value: 'middle eastern', description: 'Someone whose origins are in the Middle East' },
                                                                    { value: 'native hawaiian/pacific islander', description: 'A person having origins in any of the original peoples of Hawaii, Guam, Samoa, or other Pacific Islands (and don\t skimp on the rum!)' },
                                                                    { value: 'other', description: 'Some other racial makeup' },
                                                                    { value: 'mutt', description: 'Someone whose racial identity is muddied by generations of cross-breeding' },
                                                                  ])

FieldTemplate.find_or_create_by(name: 'cock length').field_values.create([
                                                                           { value: '[not entered]', description: 'The user hasn\'t selected a cock length (yet)', default: true },
                                                                           { value: '½"', description: '½"' },
                                                                           { value: '1"', description: '1"' },
                                                                           { value: '1 ½"', description: '1 ½"' },
                                                                           { value: '2"', description: '2"' },
                                                                           { value: '2 ½"', description: '2 ½"' },
                                                                           { value: '3"', description: '3"' },
                                                                           { value: '3 ½"', description: '3 ½"' },
                                                                           { value: '4"', description: '4"' },
                                                                           { value: '4 ½"', description: '4 ½"' },
                                                                           { value: '5"', description: '5"' },
                                                                           { value: '5 ½"', description: '5 ½"' },
                                                                           { value: '6"', description: '6"' },
                                                                           { value: '6 ½"', description: '6 ½"' },
                                                                           { value: '7"', description: '7"' },
                                                                           { value: '7 ½"', description: '7 ½"' },
                                                                           { value: '8"', description: '8"' },
                                                                           { value: '8 ½"', description: '8 ½"' },
                                                                           { value: '9"', description: '9"' },
                                                                           { value: '9 ½"', description: '9 ½"' },
                                                                           { value: '10"', description: '10"' },
                                                                           { value: '10 ½"', description: '10 ½"' },
                                                                           { value: '11"', description: '11"' },
                                                                           { value: '11 ½"', description: '11 ½"' },
                                                                           { value: '12"', description: '12"' },
                                                                           { value: '12 ½"', description: '12 ½"' },
                                                                           { value: '> 12 ½"', description: '> 12 ½"' },
                                                                         ])

FieldTemplate.find_or_create_by(name: 'cock girth').field_values.create([
                                                                          { value: '[not entered]', description: 'The user hasn\'t selected a cock girth (yet)', default: true },
                                                                          { value: '½"', description: '½"' },
                                                                          { value: '¾"', description: '¾"' },
                                                                          { value: '1"', description: '1"' },
                                                                          { value: '1 ¼"', description: '1 ¼"' },
                                                                          { value: '1 ½"', description: '1 ½"' },
                                                                          { value: '2 ¾"', description: '2 ¾"' },
                                                                          { value: '2"', description: '2"' },
                                                                          { value: '2 ¼"', description: '2 ¼"' },
                                                                          { value: '2 ½"', description: '2 ½"' },
                                                                          { value: '2 ¾"', description: '2 ¾"' },
                                                                          { value: '3"', description: '3"' },
                                                                          { value: '3 ¼"', description: '3 ¼"' },
                                                                          { value: '3 ½"', description: '3 ½"' },
                                                                          { value: '3 ¾"', description: '3 ¾"' },
                                                                          { value: '4"', description: '4"' },
                                                                          { value: '4 ¼"', description: '4 ¼"' },
                                                                          { value: '4 ½"', description: '4 ½"' },
                                                                          { value: '4 ¾"', description: '4 ¾"' },
                                                                          { value: '5"', description: '5"' },
                                                                          { value: '5 ¼"', description: '5 ¼"' },
                                                                          { value: '5 ½"', description: '5 ½"' },
                                                                          { value: '5 ¾"', description: '5 ¾"' },
                                                                          { value: '6"', description: '6"' },
                                                                          { value: '6 ¼"', description: '6 ¼"' },
                                                                          { value: '6 ½"', description: '6 ½"' },
                                                                          { value: '6 ¾"', description: '6 ¾"' },
                                                                          { value: '7"', description: '7"' },
                                                                          { value: '7 ¼"', description: '7 ¼"' },
                                                                          { value: '7 ½"', description: '7 ½"' },
                                                                          { value: '7 ¾"', description: '7 ¾"' },
                                                                          { value: '8"', description: '8"' },
                                                                          { value: '8 ¼"', description: '8 ¼"' },
                                                                          { value: '8 ½"', description: '8 ½"' },
                                                                          { value: '8 ¾"', description: '8 ¾"' },
                                                                          { value: '9"', description: '9"' },
                                                                          { value: '9 ¼"', description: '9 ¼"' },
                                                                          { value: '9 ½"', description: '9 ½"' },
                                                                          { value: '9 ¾"', description: '9 ¾"' },
                                                                          { value: '10"', description: '10"' },
                                                                          { value: '> 10"', description: '> 10"' },
                                                                        ])

FieldTemplate.find_or_create_by(name: 'smoker').field_values.create([
                                                                      { value: '[not entered]', description: 'The user hasn\'t selected whether he smokes (yet)', default: true },
                                                                      { value: 'yes, heavily', description: 'the user smokes a lot' },
                                                                      { value: 'yes', description: 'the user smokes' },
                                                                      { value: 'socially', description: 'the user smokes when he\'s out with friends' },
                                                                      { value: 'quitting', description: 'the user is trying to quit smoking' },
                                                                      { value: 'no', description: 'the user doesn\'t smoke' },
                                                                      { value: 'fuck no', description: 'the user has never touched a cigarette in his life' },
                                                                    ])

FieldTemplate.find_or_create_by(name: 'drinker').field_values.create([
                                                                       { value: '[not entered]', description: 'The user hasn\'t selected whether he drinks alcohol (yet)', default: true },
                                                                       { value: 'alcoholic', description: 'the user is an alcoholic' },
                                                                       { value: 'yes, heavily', description: 'the user drinks a lot' },
                                                                       { value: 'yes', description: 'the user drinks alcohol' },
                                                                       { value: 'socially', description: 'the user drinks alcohol when he\'s out with friends' },
                                                                       { value: 'quitting', description: 'the user is trying to quit drinking' },
                                                                       { value: 'no', description: 'the user doesn\'t drink alcohol' },
                                                                       { value: 'in recovery', description: 'the user is in recovery from alcoholism' },
                                                                       { value: 'teetotaler', description: 'the user has never touched alcohol' },
                                                                     ])

FieldTemplate.find_or_create_by(name: 'dominance').field_values.create([
                                                                         { value: '[not entered]', description: 'The user hasn\'t selected how "dominant" he is (yet)', default: true },
                                                                         { value: 'total faggot', description: '100% fag - A total submissive faggot.  Not a bone of dominance in its body.  He lives omly to serve at the feet of real Alpha Men.' },
                                                                         { value: 'faggot',
                                                                           description: '90% fag/10% dom - A faggot that knows its place in this world is at the feet of real Alpha Men.  No dominance in its body, save for a fleeting glimmer of self-confidence before it comes to its senses and ' \
                                                                                        'remembers its true place and purpose.' },
                                                                         { value: 'mostly fag', description: '80% fag/20% dom - Mostly a faggot.  Might stand up for itself once in a while but it\'s not comfortable doing it and looks hella dumb trying.' },
                                                                         { value: 'sub', description: '70% sub/30% dom - Submissive, but not a faggot.  Has some self-respect.  Stands up for himself occasionally and has his own life apart from the Alphas whom he serves.' },
                                                                         { value: 'switchy sub', description: '60% sub/40% dom - Switchy sub.  A switch who leans sub.  Might dom occasionally, but prefers to be sub.' },
                                                                         { value: 'switch', description: '50% sub/50% dom - Equal parts dom and sub.' },
                                                                         { value: 'switchy dom', description: '60% dom/40% sub - Switchy dom.  A switch who leans dom.  Might sub occasionally, but prefers to be dom.' },
                                                                         { value: 'dom', description: '70% dom/30% sub - Predominantly dominant, but might enjoy subbing for the right guy or under the right circumstances.' },
                                                                         { value: 'mostly dom', description: '80% dom/20% sub - Mostly dominant, but not an arrogant asshole about it.  Knows how to let his hair down on occasion.' },
                                                                         { value: 'beta dom', description: '90% dom/10% sub - Mostly dominant; might defer (but never submit) to an alpha dom' },
                                                                         { value: 'alpha dom', description: '100% dom - Total dominant arrogant as fuck Alpha male.  This man exudes dominance whenever he walks into a room.  He NEVER submits.  To anyone.' },
                                                                       ])

FieldTemplate.find_or_create_by(name: 'drug use').field_values.create([
                                                                        { value: '[not entered]', description: 'The user hasn\'t selected whether he uses recreational drugs (yet)',
                                                                          default: true },
                                                                        { value: 'addict', description: 'the user is a drug addict' },
                                                                        { value: 'junkie', description: 'the user is a junkie' },
                                                                        { value: 'yes, heavily', description: 'the user uses recreational drugs a lot' },
                                                                        { value: 'yes', description: 'the user uses recreational drugs' },
                                                                        { value: 'socially', description: 'the user uses recreational drugs when he\'s out with friends' },
                                                                        { value: 'quitting', description: 'the user is trying to quit using recreational drugs' },
                                                                        { value: 'no', description: 'the user doesn\'t use recreational drugs' },
                                                                        { value: 'in recovery', description: 'the user is in recovery from drug addiction' },
                                                                        { value: 'fuck no', description: 'the user has never and will never use recreational drugs' },
                                                                      ])

FieldTemplate.find_or_create_by(name: 'drugs of choice').field_values.create([
                                                                               { value: '[not entered]', description: 'the user hasn\'t entered any drugs of choice (yet)', default: true },
                                                                             ])

FieldTemplate.find_or_create_by(name: 'kinks/fetishes').field_values.create([
                                                                              { value: '[not entered]', description: 'the user hasn\'t entered any kinks or fetishes (yet)', default: true },
                                                                            ])

FieldTemplate.find_or_create_by(name: 'body hair').field_values.create([
                                                                         { value: '[not entered]', description: 'the user hasn\'t entered his body hair (yet)', default: true },
                                                                         { value: 'naturally smooth', description: 'the user has a naturally smooth body' },
                                                                         { value: 'shaved smooth', description: 'the user shaves his hair off' },
                                                                         { value: 'trimmed', description: 'the user trims his body hair' },
                                                                         { value: 'some hair', description: 'the user has some hair on his body' },
                                                                         { value: 'hairy', description: 'the user is hairy' },
                                                                         { value: 'very hairy', description: 'the user has lots of body hair' },
                                                                         { value: 'sasquatch', description: 'the user might as well be fucking Bigfoot!' },
                                                                       ])

FieldTemplate.find_or_create_by(name: 'height').field_values.create([
                                                                      { value: '[not entered]', description: 'the user hasn\'t entered his height (yet)', default: true },
                                                                      { value: '2ft', description: '2ft' },
                                                                      { value: '2ft 1in', description: '2ft 1in' },
                                                                      { value: '2ft 2in', description: '2ft 2in' },
                                                                      { value: '2ft 3in', description: '2ft 3in' },
                                                                      { value: '2ft 4in', description: '2ft 4in' },
                                                                      { value: '2ft 5in', description: '2ft 5in' },
                                                                      { value: '2ft 6in', description: '2ft 6in' },
                                                                      { value: '2ft 7in', description: '2ft 7in' },
                                                                      { value: '2ft 8in', description: '2ft 8in' },
                                                                      { value: '2ft 9in', description: '2ft 9in' },
                                                                      { value: '2ft 10in', description: '2ft 10in' },
                                                                      { value: '2ft 11in', description: '2ft 11in' },
                                                                      { value: '3ft', description: '3ft' },
                                                                      { value: '3ft 1in', description: '3ft 1in' },
                                                                      { value: '3ft 2in', description: '3ft 2in' },
                                                                      { value: '3ft 3in', description: '3ft 3in' },
                                                                      { value: '3ft 4in', description: '3ft 4in' },
                                                                      { value: '3ft 5in', description: '3ft 5in' },
                                                                      { value: '3ft 6in', description: '3ft 6in' },
                                                                      { value: '3ft 7in', description: '3ft 7in' },
                                                                      { value: '3ft 8in', description: '3ft 8in' },
                                                                      { value: '3ft 9in', description: '3ft 9in' },
                                                                      { value: '3ft 10in', description: '3ft 10in' },
                                                                      { value: '3ft 11in', description: '3ft 11in' },
                                                                      { value: '4ft', description: '4ft' },
                                                                      { value: '4ft 1in', description: '4ft 1in' },
                                                                      { value: '4ft 2in', description: '4ft 2in' },
                                                                      { value: '4ft 3in', description: '4ft 3in' },
                                                                      { value: '4ft 4in', description: '4ft 4in' },
                                                                      { value: '4ft 5in', description: '4ft 5in' },
                                                                      { value: '4ft 6in', description: '4ft 6in' },
                                                                      { value: '4ft 7in', description: '4ft 7in' },
                                                                      { value: '4ft 8in', description: '4ft 8in' },
                                                                      { value: '4ft 9in', description: '4ft 9in' },
                                                                      { value: '4ft 10in', description: '4ft 10in' },
                                                                      { value: '4ft 11in', description: '4ft 11in' },
                                                                      { value: '5ft', description: '5ft' },
                                                                      { value: '5ft 1in', description: '5ft 1in' },
                                                                      { value: '5ft 2in', description: '5ft 2in' },
                                                                      { value: '5ft 3in', description: '5ft 3in' },
                                                                      { value: '5ft 4in', description: '5ft 4in' },
                                                                      { value: '5ft 5in', description: '5ft 5in' },
                                                                      { value: '5ft 6in', description: '5ft 6in' },
                                                                      { value: '5ft 7in', description: '5ft 7in' },
                                                                      { value: '5ft 8in', description: '5ft 8in' },
                                                                      { value: '5ft 9in', description: '5ft 9in' },
                                                                      { value: '5ft 10in', description: '5ft 10in' },
                                                                      { value: '5ft 11in', description: '5ft 11in' },
                                                                      { value: '6ft', description: '6ft' },
                                                                      { value: '6ft 1in', description: '6ft 1in' },
                                                                      { value: '6ft 2in', description: '6ft 2in' },
                                                                      { value: '6ft 3in', description: '6ft 3in' },
                                                                      { value: '6ft 4in', description: '6ft 4in' },
                                                                      { value: '6ft 5in', description: '6ft 5in' },
                                                                      { value: '6ft 6in', description: '6ft 6in' },
                                                                      { value: '6ft 7in', description: '6ft 7in' },
                                                                      { value: '6ft 8in', description: '6ft 8in' },
                                                                      { value: '6ft 9in', description: '6ft 9in' },
                                                                      { value: '6ft 10in', description: '6ft 10in' },
                                                                      { value: '6ft 11in', description: '6ft 11in' },
                                                                      { value: '7ft', description: '7ft' },
                                                                      { value: '7ft 1in', description: '7ft 1in' },
                                                                      { value: '7ft 2in', description: '7ft 2in' },
                                                                      { value: '7ft 3in', description: '7ft 3in' },
                                                                      { value: '7ft 4in', description: '7ft 4in' },
                                                                      { value: '7ft 5in', description: '7ft 5in' },
                                                                      { value: '7ft 6in', description: '7ft 6in' },
                                                                      { value: '7ft 7in', description: '7ft 7in' },
                                                                      { value: '7ft 8in', description: '7ft 8in' },
                                                                      { value: '7ft 9in', description: '7ft 9in' },
                                                                      { value: '7ft 10in', description: '7ft 10in' },
                                                                      { value: '7ft 11in', description: '7ft 11in' },
                                                                    ])

FieldTemplate.find_or_create_by(name: 'weight').field_values.create([
                                                                      { value: '[not entered]', description: 'the user hasn\'t entered his weight (yet)', default: true },
                                                                      { value: '90lbs', description: '90lbs' },
                                                                      { value: '95lbs', description: '95lbs' },
                                                                      { value: '100lbs', description: '100lbs' },
                                                                      { value: '105lbs', description: '105lbs' },
                                                                      { value: '110lbs', description: '110lbs' },
                                                                      { value: '115lbs', description: '115lbs' },
                                                                      { value: '120lbs', description: '120lbs' },
                                                                      { value: '125lbs', description: '125lbs' },
                                                                      { value: '130lbs', description: '130lbs' },
                                                                      { value: '135lbs', description: '135lbs' },
                                                                      { value: '140lbs', description: '140lbs' },
                                                                      { value: '145lbs', description: '145lbs' },
                                                                      { value: '150lbs', description: '150lbs' },
                                                                      { value: '155lbs', description: '155lbs' },
                                                                      { value: '160lbs', description: '160lbs' },
                                                                      { value: '165lbs', description: '165lbs' },
                                                                      { value: '170lbs', description: '170lbs' },
                                                                      { value: '175lbs', description: '175lbs' },
                                                                      { value: '180lbs', description: '180lbs' },
                                                                      { value: '185lbs', description: '185lbs' },
                                                                      { value: '190lbs', description: '190lbs' },
                                                                      { value: '195lbs', description: '195lbs' },
                                                                      { value: '200lbs', description: '200lbs' },
                                                                      { value: '205lbs', description: '205lbs' },
                                                                      { value: '210lbs', description: '210lbs' },
                                                                      { value: '215lbs', description: '215lbs' },
                                                                      { value: '220lbs', description: '220lbs' },
                                                                      { value: '225lbs', description: '225lbs' },
                                                                      { value: '230lbs', description: '230lbs' },
                                                                      { value: '235lbs', description: '235lbs' },
                                                                      { value: '240lbs', description: '240lbs' },
                                                                      { value: '245lbs', description: '245lbs' },
                                                                      { value: '250lbs', description: '250lbs' },
                                                                      { value: '255lbs', description: '255lbs' },
                                                                      { value: '260lbs', description: '260lbs' },
                                                                      { value: '265lbs', description: '265lbs' },
                                                                      { value: '270lbs', description: '270lbs' },
                                                                      { value: '275lbs', description: '275lbs' },
                                                                      { value: '280lbs', description: '280lbs' },
                                                                      { value: '285lbs', description: '285lbs' },
                                                                      { value: '290lbs', description: '290lbs' },
                                                                      { value: '295lbs', description: '295lbs' },
                                                                      { value: '300lbs', description: '300lbs' },
                                                                      { value: '305lbs', description: '305lbs' },
                                                                    ])
