# Use the base image
FROM linuxserver/mastodon:latest AS base

# Set the working directory
WORKDIR /app/www

# Copy Gemfile and Gemfile.lock
COPY Gemfile .
COPY Gemfile.lock .
COPY Gemfile.lock .
COPY ./app .
COPY ./lib .
COPY ./vendor .
COPY ./streaming .
COPY ./spec .
COPY ./spec .
COPY ./public .
COPY ./config .
COPY ./package.json .
COPY ./jsconfig.json .
# COPY ./node_modules .
COPY ./config/nginx /etc/nginx

FROM base AS with-src

# Install necessary build dependencies
RUN apk update && \
    apk add --no-cache \
    autoconf \
    automake \
    build-base \
    cmake \
    git \
    gdbm-dev \
    glib-dev \
    gmp-dev \
    icu-dev \
    libidn-dev \
    postgresql-dev \
    openssl-dev \
    libtool \
    meson \
    nasm \
    pkgconfig \
    shared-mime-info \
    xz \
    # libvips components
    libexif-dev \
    expat-dev \
    gobject-introspection-dev \
    libheif-dev \
    libimagequant-dev \
    libjpeg-turbo-dev \
    lcms2-dev \
    orc-dev \
    tiff-dev \
    libwebp-dev \
    # ffmpeg components
    dav1d-dev \
    xz-dev \
    lame-dev \
    opus-dev \
    snappy-dev \
    libvpx-dev \
    x264-dev \
    x265-dev \
    libvorbis-dev \
    ruby \
    ruby-dev \
    yaml-dev

RUN apk add --no-cache \
    libtool \
    linux-headers \
    libc-dev \
    protobuf-dev \
    protobuf-c-dev

FROM with-src AS with-dependencies

RUN git clone https://github.com/rbenv/rbenv.git ~/.rbenv && \
    echo 'export PATH="$HOME/.rbenv/bin:/root/.rbenv/shims/ruby:$PATH"' >> ~/.bashrc && \
    echo 'eval "$(rbenv init -)"' >> ~/.bashrc && \
    exec bash && \
    cp $HOME/.bashrc $HOME/.profile \
    cp $HOME/.bashrc $HOME/.shrc && \
    git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build &&  \
    RUBY_CONFIGURE_OPTS=--with-jemalloc rbenv install 3.3.4 && \
    rbenv global 3.3.4

FROM with-dependencies AS with-ruby

# Set environment variables for compilation
ENV CFLAGS="-Wno-error=format-security -O2" \
    CPPFLAGS="-Wno-error=format-security"

# Install Bundler
RUN gem install bundler --no-document

FROM with-ruby AS with-bundler

# Set bundler to non-frozen mode and install gems
RUN exec bash && \
    bundle config set frozen false && \
    bundle update && \
    bundle install

FROM with-bundler AS mastodon