FROM ghcr.io/justinwritescode/mastodon:thebackroom.life AS base


SHELL [ "bash", "-c" ]

EXPOSE 808 2222

WORKDIR /opt/mastodon/bin

ENTRYPOINT [ "bash", "entrypoint", "sidekiq" ]

LABEL org.opencontainers.image.description="Sidekiq for TheBackroom.life"
LABEL org.opencontainers.image.source="https://github.com/justinwritescode/mastodon"
LABEL org.opencontainers.image.licenses="MIT"
