#!/bin/bash

# Directory containing the files
DIRECTORY="/config/nginx/site-confs/"

# Ensure DIRECTORY variable is not empty
if [ -z "$DIRECTORY" ]; then
echo "Please specify a directory."
exit 1
fi

# Check if the directory exists
if [ ! -d "$DIRECTORY" ]; then
echo "Directory does not exist."
exit 1
fi

# Loop through all files in the directory
for file in "$DIRECTORY"/*; do
# Check if it is a file (not a directory)
if [ -f "$file" ]; then
    ./replace_environment_vars_in_file "$File"
    echo "Replaced environment variables in $file."
fi
done

nginx -s reload

echo "Replaced environment variables for all files in $DIRECTORY."