#!/usr/bin/with-contenv bash
# shellcheck shell=bash

export NODE_ENV=production
export PATH="${PATH}:/app/www/bin"

echo "Starting SSHD server...";

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 2222" \
    service ssh start
