# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - thebackroomlife

on:
  push:
    branches:
      - thebackroombranding
    tags:
      - blv*
  workflow_dispatch:

concurrency: 
  group: Continuous Deployment - TheBackroom.life
  cancel-in-progress: true

permissions: write-all

env:
  MASTODON_VERSION_METADATA: ${{ github.sha }}

jobs:
  build-thebackroom-life:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        
    - uses: ./.github/actions/build-and-push-docker-image
      id: build-mastodon
      name: 'Build TheBackroom.life'
      with:
        github-password: ${{ github.token }} 
        acr-password: ${{ secrets.AZURECR_KEY }}
        dockerfile: ./Dockerfile.thebackroom.life
        tag: thebackroom.life

  build-thebackroom-streaming:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build-and-push-docker-image
      id: build-streaming
      name: 'Build Streaming.TheBackroom.life'
      with:
        github-password: ${{ github.token }} 
        acr-password: ${{ secrets.AZURECR_KEY }}
        dockerfile: ./streaming/Dockerfile
        tag: streaming.thebackroom.life

  build-thebackroom-sidekiq:
    needs: build-thebackroom-life
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-and-push-docker-image
        id: build-sidekiq
        name: 'Build Sidekiq.TheBackroom.life'
        with:
          github-password: ${{ github.token }} 
          acr-password: ${{ secrets.AZURECR_KEY }}
          dockerfile: ./Dockerfile.sidekiq.thebackroom.life
          tag: sidekiq.thebackroom.life
    
  deploy-to-thebackroom-life:
    runs-on: ubuntu-latest
    needs: 
      - build-thebackroom-life
    environment:
      name: 'thebackroom.life'
      url: ${{ steps.deploy-to-thebackroom-life.webapp-url }}

    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Azure Web App
      id: deploy-to-thebackroom-life
      uses: azure/webapps-deploy@v3.0.2
      with:
        app-name: 'thebackroomlife'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_THEBACKROOMLIFE }}
        images: ${{ steps.build-mastodon.outputs.image }}

  deploy-to-thebackroom-streaming:
    runs-on: ubuntu-latest
    needs: 
      - build-thebackroom-streaming
    environment:
      name: 'streaming.thebackroom.life'
      url: ${{ steps.deploy-to-thebackroom-streaming.webapp-url }}

    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Azure Web App
      id: deploy-to-thebackroom-streaming
      uses: azure/webapps-deploy@v3.0.2
      with:
        app-name: 'thebackroomlife-streaming'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_STREAMING }}
        images: ${{ steps.build-streaming.outputs.image }}

  deploy-to-thebackroom-sidekiq:
    runs-on: ubuntu-latest
    needs: 
      - build-thebackroom-sidekiq
    environment:
      name: 'sidekiq.thebackroom.life'
      url: ${{ steps.deploy-to-thebackroom-sidekiq.webapp-url }}

    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Azure Web App
      id: deploy-to-thebackroom-sidekiq
      uses: azure/webapps-deploy@v3.0.2
      with:
        app-name: 'thebackroomlife-sidekiq'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_SIDEKIQ }}
        images: ${{ steps.build-sidekiq.outputs.image }}
